#!/bin/bash
#
# CaveSpectre's Masternode Scan Script
#       Any questions, find me on discord: CaveSpectre#1277
#       or email crypto@pontificatingnobody.com
#
#       Any tips (Appreciated but not expected)
#         ETH & Tokens: 0xbd389f6622083b967c32026706fde83e599b7cfa
#         BTC: 1LcaRjBWuR9h42wx4Emh9xBMke4rLYyf74
#         GambleCoin: CQTAhA9R28nHAuRpRqmf6WAJkMYwEYBY9A
#
#    03-Feb-2019 - Initial Creation
#
#  This script will check if any of the configured coins are in your execution
#  path, and if so, will find the conf files for the coin, and execute master-
#  node status for said coins.  It will parse the output to determine if it's
#  up and running, if it's completely failed, or if it's ready to be started
#  from the wallet.  The supported coins is a living configuration; as many
#  coins have different text matches.  This script is designed to have the
#  match regular expression for each coin to be configurable.  This will
#  evolve over time.

declare -A coins=(
  [adirondack]=status.*success
  [alanis]=status.*success
  [aprcoin]=status.*success
  [authoracoin]=message.*success
  [axe]=status.*success
  [coin2play]=message.*success
  [dacash]=status.*success
  [dextro]=status.*success
  [emrals]=status.*success
  [essence]=status.*success
  [fantasygold]=message.*success
  [gamblecoin]=message.*success
  [idapay]=status.*success
  [lightpaycoin]=message.*success
  [linuxpay]=status.*success
  [omegacoin]=status.*success
  [primestone]=message.*success
  [stakecube]=message.*success
  [solarium]=message.*success
  [ucc]=message.*success
  [ultranatum]=status.*success
  [wilo]=status.*success
  [zenad]=status.*success
)

homedir=~/   # set this to the highest parent directory to speed up the search

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m'

# Make the array of coins;
# foreach coin
#  whereis coin-cli -> save find time. support more coins
# make the good array
# make the wait array
# goodregex=${goodarray[$coin]
# waitregex=${waitarray[$coin]

for i in "${!coins[@]}"
do

 # look for the cli, and skip if it doesn't exist
 whereis=`whereis $i-cli`
 whereis="${whereis#*:}"
 if [[ ! $whereis = *[!\ ]* ]]; then
  continue
 fi

 goodregex=${coins[$i]}
 mnsregex="Hot.node"  # Needs to be configured into the configure array
 # find all the conf files for the coin
 find $homedir -name $i.conf -print | while read -r line
 do
   datadir="${line%/*}" # remove the conf file name
   if $i-cli -datadir=$datadir masternode status 2>&1 \
      | grep -e $goodregex > /dev/null 2>&1
   then
     echo -e "$datadir: ${GREEN}passed${NC}"
   else
     # clean this whole thing up later
     if $i-cli -datadir=$datadir masternode status 2>&1 \
      | grep -e $mnsregex > /dev/null 2>&1
     then
       echo -e "$datadir: ${YELLOW}restart alias${NC}"
     else
       echo -e "$datadir: ${RED}failed${NC} ( $i-cli " \
               "-datadir=$datadir masternode status )"
     fi
   fi

 done
done
